# Generated by Django 5.2.6 on 2025-09-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Inventory',
            fields=[
                ('Plate_No', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Car_Model', models.CharField(max_length=100)),
                ('Car_Type', models.CharField(max_length=20)),
                ('Mileage', models.IntegerField()),
                ('Engine_Type', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
