# Generated by Django 5.2.6 on 2025-09-21 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0002_car_inventory_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_inventory',
            old_name='Car_Type',
            new_name='Car_Color',
        ),
        migrations.RenameField(
            model_name='car_inventory',
            old_name='Engine_Type',
            new_name='Car_Manufacturer',
        ),
    ]
